FROM node:alpine

WORKDIR /usr/src/app
ENV NODE_OPTIONS=--max-old-space-size=256

RUN npm install -g pnpm

COPY . .

RUN pnpm install --frozen-lockfile

# Only generate Prisma client once
RUN pnpm run db:generate

# Build in steps to reduce memory usage
RUN pnpm run build --filter=@repo/common
RUN pnpm run build --filter=@repo/backend-common
RUN pnpm run build --filter=@repo/db
RUN pnpm run build --filter=http-backend

EXPOSE 3002

CMD ["pnpm", "run", "start", "--filter=http-backend"]
